local config = {
	enabled_modules = {
		retrievehands = true,
		deckthebalatro = true,
		suitedunimpresseddispleasedoverlord = true,
		dankranks = false, --not real
		skinmeadeck = true,
		enhancable = true,
		vouchme = true,
		moreconsumables = true,
		basicoddities = true,
		blindtoallbutthevideo = true,
		tagimit = true, --soon(tm)
		jokerstamps = true,
		lookslikethejokers = true,
		editiontomeetya = true,
		hamspect = true,
		totallyrealzodiac = true,
		bossmyjokers = true,
		selbamusnocerom = true,
		threeerror = true,
		joyinautumn = true,
		shattermyjokersintopieces = true,
		effectsonmyjokersitsmorelikelythanyouthink = true,
		transgirlswhobooster = true,
		stakemepls = true,
		skinnington = true,
		emojiokers = true,
	},
	enabled_jokers = {
		helpful_joker = true,
		dutiful_joker = true,
		frivolous_joker = true,
		groaning_joker = true,
		wayfarer = true,
		power_of_unity = true,
		chaotic = true,
		standardized = true,
		nonstandard = true,
		gift_from_the_void = true,
		lord_of_the_meek = true,
		mirage_joker = true,
		transfusion = true,
		placeholder_joker = true,
		filler_card = true,
		test_print = true,
		garden = true,
		clown_posse = true,
		stellar_alignment = true,
		paint_mixer = true,
		psychic_double_reacharound = true,
		knight_of_heart = true,
		witch_of_mind = true,
		lord_of_void = true,
		funny_fertilizer = true,
		highest_number = true,
		daggerkind = true,
		bladekind = true,
		pokerkind = true,
		combat_capability = true,
		pseudoscratch = true,
		astront = true,
		torrential = true,
		landlord = true,
		court_of_jokers = true,
		lost_sock = true,
		the_csi = true,
		junk_collector = true,
		exorcist = true,
		gallows_humor = true,
		common_ground = true,
		tombstone = true,
		gem_joker = true,
		discarded_vessel = true,
		afterlife_archive = true,
		jokermancer = true,
		gaudy_bracelet = true,
		twisted_mind = true,
		joke_book_of_the_dead = true,
		gravedigger = true,
		matchbook = true,
		dark_hallway = true,
		triplicate_soul = true,
		grasp_of_emptiness = true,
		shutin = true,
		ace_in_the_hole = true,
		topple_the_titans = true,
		underdogs_secret = true,
		amalgamiter = true,
		celestial_awe = true,
		somber_snowfall = true,
		jack_of_all_trades = true,
		all_lucky_sevens = true,
		quantum_grass = true,
		twin_stella = true,
		lunar_grave = true,
	},
	enabled_consumables = {
		--tarot
		universe = true,
		void = true,
		happy_squirrel = true,
		artist = true,
		veteran = true,
		juggler = true,
		drunkard = true,
		grass = true,
		bone = true,
		collector = true,
		cycle = true,
		joker = true,
		
		--planets
		comet = true,
		meteor = true,
		satellite = true,
		moon = true,
		station = true,
		dysnomia = true,
		planet_s = true,
		planet_h = true,
		planet_c = true,
		planet_d = true,
		shooting_star = true,
		chill_moon = true,
		
		--spectrals
		chance = true,
		offering = true,
		tribute = true,
		sacrifice = true,
		scry = true,
		lotus = true,
		phantom = true,
		-- following require jokerstamps and respective stamp if applicable
			mischief = true,
			comedy = true,
			tragedy = true,
			whimsy = true,
			entropy = true,
			wonder = true,
			macabre = true,
			duplicity = true,
			banana = true,
			artifice = true,
		quest_bed = true,
		
		--oddities
		one_jollar = true,
		two_jollar = true,
		five_jollar = true,
		ten_jollar = true,
		twenty_jollar = true,
		pot_of_joker = true,
		green_chip = true,
		yellow_chip = true,
		red_blue_chip = true,
		purple_chip = true,
		power_chip = true,
		silica_packet = true,
		jimbobread_man = true,
		jimbobread_man_half = true,
		narwhal_horn = true,
		cultist_potion = true,
		fire_potion = true,
		snecko_potion = true,
		energy_potion = true,
		vote_sticker = true,
		cpu_memory = true,
		estradiol = true,
		faded_voucher = true,
		empty_bottle = true,
		box_of_rocks = true,
		bag_of_stardust = true,
		jar_of_dirt = true,
		calcium = true,
		scrap_metal = true,
		fossil = true,
		gift_of_the_knight = true,
	},
	enabled_vouchers = {
		spectral_merchant = true,
		spectral_tycoon = true,
		-- following requires jokerstamps
		stamp_savvy = true,
		stamp_coupon = true,
		-- following requires oddityapi
		oddity_merchant = true,
		oddity_tycoon = true,

		wheel_of_wheel_of_fortune = true,
		ceaseless_wheel = true,

		plus_four = true,
		x_four = true,
	},
	enabled_seals = {
	},
	enabled_stamps = {
		jimbo = true,
		todd = true,
		steven = true,
		chaos = true,
		andy = true,
		mr_bones = true,
		vampire = false,
		sock_and_buskin = true,
		hiker = false,
		gros_michel = true,
		blueprint = true,
		dusk = true,
	},
	enabled_enhancements = {
		loop = false,
		grass = true,
		dirt = true,
		star = true,
		bone = true,
		soulbound = true,
		jewel = true,
	},
	enabled_editions = {
		gilded = true,
	},
	enabled_decks = {
		wheel_of_fortune_deck = true,
		collectors_deck = true,
	},
	enabled_blinds = {
		fehu = true,
		uruz = true,
		thorn = true,
		ansuz = true,
		raido = true,
		kaun = true,
		gyfu = true,
		wynn = true,
		hagalaz = true,
		naudiz = true,
		isaz = true,
		jera = true,
		eihaz = true,
		pertho = true,
		algiz = true,
		sowilo = true,
		tiwaz = true,
		berkanan = true,
		ehwaz = true,
		mannaz = true,
		laguz = true,
		ingwaz = true,
		dagaz = true,
		othala = true,
	},
	enabled_tags = {
		gilded = true,
		collector = true,
	},
	enabled_aspects = {
		breath = true,
		life = true,
		light = true,
		time = true,
		heart = true,
		rage = true,
		blood = true,
		doom = true,
		void = true,
		space = true,
		mind = true,
		hope = true,
	},
	enabled_materials = {
	},
	enabled_recipes = {
	},
	enabled_boosters = {
		option_select = true,
	},
	enabled_stakes = {
		culmination = true,
	},
	enabled_deckskins = {
	},
	mechanics = {
	},
}

return config